name: descent-ff

channels:
  - conda-forge
  - openeye

dependencies:

  - python >=3.10
  - pip

  - smee    >=0.8.0
  - descent >=0.4.0

  - click

  # Parameterization
  - openff-toolkit
  - openff-interchange
  - rdkit
  - openeye-toolkits=2022.1.1

  # Training
  - tensorboard
  - tensorboardX

  # Interface with Espaloma
  - dgl

  # Dev
  - pre-commit
  - ruff
